# Basic Config
esphome:
  name: $device_name
  platform: $device_platform
  board: $device_board

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
   # Static IP
  manual_ip:
    static_ip: $wifi_ip
    gateway: !secret network_gateway
    subnet: !secret network_subnet
    dns1: !secret network_dns1
    dns2: !secret network_dns2
  domain: !secret network_domain
  # Create AP if not able to connect to wifi
  ap:
    ssid: $device_name
    password: !secret wifi_password

logger:
  baud_rate: 0  # (UART logging interferes with cse7766)

api:
  encryption:
    key: !secret api_encryption

mqtt:
  broker: !secret mqtt_broker
  topic_prefix: $mqtt_topic_prefix

ota:
  password: !secret esp_ota

# Enable web hosting when wifi can not connect to be able to
# update wifi connection or firmware
captive_portal:
