# Device Specific Config
logger:
  baud_rate: 0 # (UART logging interferes with cse7766)

uart:
  rx_pin: RX
  baud_rate: 4800
  parity: EVEN # required since 2024-08

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: "${device_name} Button"
    on_press:
      - switch.toggle: relay
  - platform: status
    name: "${device_name} Status"

sensor:
  - platform: wifi_signal
    id: wifi_connection
    name: "${device_name} WiFi Signal"
    update_interval: 2s

  - platform: cse7766
    current:
      name: "${device_name} Current"
      id: current
      state_class: measurement
      device_class: current
      unit_of_measurement: A
      accuracy_decimals: 1
      filters:
        - throttle_average: 2s
    
    voltage:
      name: "${device_name} Voltage"
      id: voltage
      state_class: measurement
      device_class: voltage
      unit_of_measurement: V
      accuracy_decimals: 1
      filters:
        - throttle_average: 2s
    
    power:
      name: "${device_name} Power"
      id: power
      state_class: measurement
      device_class: power
      unit_of_measurement: W
      accuracy_decimals: 1
      filters:
        - throttle_average: 2s

    energy:
      name: "Energy"
      accuracy_decimals: 1
      filters:
        - throttle_average: 2s

    apparent_power:
      name: "Apparent Power"
      accuracy_decimals: 1
      filters:
        - throttle_average: 2s

    power_factor:
      name: "Power Factor"
      accuracy_decimals: 1
      filters:
        - throttle_average: 2s
  
  - platform: total_daily_energy
    name: "${device_name} Daily Energy"
    power_id: power
  
  - platform: integration
    name: "${device_name} Energy Spent"
    sensor: power
    time_unit: h
    unit_of_measurement: kWh
    state_class: total_increasing
    device_class: energy
    accuracy_decimals: 2
    filters:
      - multiply: 0.001

switch:
  - platform: gpio
    name: "${device_name} Relay"
    pin: GPIO12
    id: relay
    restore_mode: ALWAYS_ON

time:
  - platform: homeassistant
    id: ha_time

status_led:
  pin:
    number: GPIO13
    inverted: True
