# Device Specific Config
uart:
  rx_pin: RX
  baud_rate: 4800

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: "$device_name Button"
    on_press:
      - switch.toggle: relay
  - platform: status
    name: "$device_name Status"

sensor:
  - platform: wifi_signal
    id: wifi_connection
    name: "$device_name WiFi Signal"
    update_interval: 10s
  - platform: cse7766
    current:
      name: "$device_name Current"
      accuracy_decimals: 1
    voltage:
      name: "$device_name Voltage"
      accuracy_decimals: 1
    power:
      name: "$device_name Power"
      accuracy_decimals: 1
      id: my_power
    update_interval: 10s
  - platform: total_daily_energy
    name: "$device_name Daily Energy"
    power_id: my_power

switch:
  - platform: gpio
    name: "$device_name Relay"
    pin: GPIO12
    id: relay
    restore_mode: ALWAYS_ON

time:
  - platform: sntp
    id: my_time

status_led:
  pin:
    number: GPIO13
    inverted: True
